=== 0xpsilocybe/HowFastUType/db/gameDataSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
		   elementFormDefault="qualified">

<xs:element name="root">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="users">
		<xs:complexType>
			<xs:element name="user">
				<xs:element name="name" type="xs:string"/>
			</xs:element>
		</xs:complexType>
	  </xs:element>
	  
      <xs:element name="highscores">
		<xs:complexType>
			<xs:element name="user">
			<xs:attribute name="nick" type="xs:string" use="required" />
				<xs:sequence>
					<xs:element name="casual">
						<xs:complexType>
							<xs:element name="score">
								<xs:sequence>
									<xs:element name="points" type="xs:integer" />
									<xs:element name="time" type="xs:integer" />
									<xs:element name="accuracy" type="xs:decimal"/>
								</xs:sequence>
							</xs:element>	
						</xs:complexType>
					</xs:element>
					
					<xs:element name="marathon">
						<xs:complexType>
							<xs:element name="score">
								<xs:sequence>
									<xs:element name="points" type="xs:integer" />
									<xs:element name="time" type="xs:integer" />
									<xs:element name="accuracy" type="xs:decimal"/>
								</xs:sequence>
							</xs:element>	
						</xs:complexType>
					</xs:element>
					
					<xs:element name="reaction">
						<xs:complexType>
							<xs:element name="score">
								<xs:sequence>
									<xs:element name="points" type="xs:integer" />
									<xs:element name="time" type="xs:integer" />
									<xs:element name="accuracy" type="xs:decimal"/>
								</xs:sequence>
							</xs:element>	
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:element>
		</xs:complexType>
	  </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== 0xpsilocybe/HowFastUType/db/gameData.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><root xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com gameDataSchema.xsd">
	<users>
		<user>
			<name>Bartek</name>
		</user>
		
		<user>
			<name>Andrzej</name>
		</user>
	<user><name>NowyUser</name></user><user><name>superuser</name></user><user><name>qwerqwt</name></user><user><name>admin</name></user><user><name>bartelemi</name></user></users>
	<highscores>
		<user nick="Bartek">
			<casual>
				<score>
					<points>100</points>
					<time>10000</time>
					<accuracy>90.2</accuracy>
				</score>
				<score>
					<points>90</points>
					<time>14000</time>
					<accuracy>88.2</accuracy>
				</score>
				<score>
					<points>200</points>
					<time>9000</time>
					<accuracy>100</accuracy>
				</score>
			<score><points>67</points><time>12000</time><accuracy>78.3</accuracy></score><score><points>7</points><time>14408</time><accuracy>100.0</accuracy></score><score><points>897</points><time>11148</time><accuracy>100.0</accuracy></score></casual>
			<marathon>
				<score>
					<points>100</points>
					<time>10000</time>
					<accuracy>90.2</accuracy>
				</score>
				<score>
					<points>90</points>
					<time>14000</time>
					<accuracy>88.2</accuracy>
				</score>
				<score>
					<points>200</points>
					<time>9000</time>
					<accuracy>100</accuracy>
				</score>
			</marathon>
			<reaction>
				<score>
					<points>100</points>
					<time>10000</time>
					<accuracy>90.2</accuracy>
				</score>
				<score>
					<points>90</points>
					<time>14000</time>
					<accuracy>88.2</accuracy>
				</score>
				<score>
					<points>200</points>
					<time>9000</time>
					<accuracy>100</accuracy>
				</score>
			</reaction>
		</user>
		
		
		
		<user nick="Andrzej">
			<casual>
				
				
								
			</casual>
			<marathon>
				
			</marathon>
			<reaction>
				
				
				
			</reaction>
		</user>
	<user nick="NowyUser"><casual/><marathon/><reaction/></user><user nick="superuser"><casual/><marathon/><reaction/></user><user nick="qwerqwt"><casual/><marathon/><reaction/></user><user nick="admin"><casual/><marathon/><reaction/></user><user nick="bartelemi"><casual/><marathon/><reaction/></user></highscores>
</root>
